services:
  - type: web
    name: expense-tracker
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --chdir expense_tracker expense_tracker.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expense-tracker-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: expense-tracker-db
    databaseName: expensetracker
    user: expensetracker
