# Generated by Django 5.2.5 on 2026-02-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_expense_options_expense_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
