# Generated by Django 5.2.5 on 2026-03-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_remove_debt_status_debtpayment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="debt",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Debt",
                "verbose_name_plural": "Debts",
            },
        ),
        migrations.AlterModelOptions(
            name="debtpayment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Debt Payment",
                "verbose_name_plural": "Debt Payments",
            },
        ),
        migrations.AlterModelOptions(
            name="expense",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
            },
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("Food", "Food"),
                    ("Transport", "Transport"),
                    ("Bills", "Bills"),
                    ("Entertainment", "Entertainment"),
                    ("Study", "Study"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
